# Generated by Django 6.1.1 on 2026-09-22 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_email', models.EmailField(blank=True, max_length=254)),
                ('role', models.CharField(default='student', max_length=20)),
                ('target_role', models.CharField(default='Cloud Solutions Architect', max_length=100)),
                ('readiness_score', models.PositiveIntegerField(default=74)),
                ('readiness_delta', models.CharField(default='+5.2% this month', max_length=20)),
                ('resume_score', models.PositiveIntegerField(default=92)),
                ('skills_acquired', models.PositiveIntegerField(default=18)),
                ('interview_rate', models.PositiveIntegerField(default=78)),
                ('critical_gaps', models.PositiveIntegerField(default=3)),
                ('certified_skills', models.PositiveIntegerField(default=12)),
                ('next_milestone', models.CharField(default='Architect', max_length=100)),
                ('weeks_to_milestone', models.PositiveIntegerField(default=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('soft', 'Soft'), ('leadership', 'Leadership')], default='technical', max_length=20)),
                ('current', models.PositiveIntegerField(default=50)),
                ('target', models.PositiveIntegerField(default=80)),
                ('status', models.CharField(choices=[('growing', 'Growing'), ('stable', 'Stable')], default='stable', max_length=10)),
                ('priority', models.CharField(choices=[('high', 'High Priority'), ('medium', 'Medium Priority'), ('low', 'Low Priority')], default='medium', max_length=10)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.profile')),
            ],
            options={
                'ordering': ['-priority', 'name'],
            },
        ),
    ]
