# Generated by Django 6.1.1 on 2026-09-29 04:11

from django.db import migrations, models


def zero_fake_metrics(apps, schema_editor):
    """Profiles with no uploaded resume were carrying invented defaults
    (readiness 74, resume score 92, ...). Those numbers were never derived
    from anything, so clear them. Profiles that do have a resume are left
    alone here and are recalculated from real data the next time the
    student opens their dashboard (or via `manage.py recompute_metrics`)."""
    Profile = apps.get_model('core', 'Profile')
    Resume = apps.get_model('core', 'Resume')
    with_resume = Resume.objects.values_list('profile_id', flat=True).distinct()
    Profile.objects.exclude(id__in=with_resume).update(
        readiness_score=0, resume_score=0, skills_acquired=0, interview_rate=0,
        critical_gaps=0, certified_skills=0, readiness_delta='',
        next_milestone='', weeks_to_milestone=0,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_learningresource_studentlearningprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='certified_skills',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='critical_gaps',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interview_rate',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='next_milestone',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='readiness_delta',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='readiness_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills_acquired',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weeks_to_milestone',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(zero_fake_metrics, migrations.RunPython.noop),
    ]
