# Generated by Django 6.1.1 on 2026-09-29 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_studentdetail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='application_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='eligibility',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='review_note',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_opportunities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='skills',
            field=models.CharField(blank=True, default='', help_text='Comma-separated, e.g. Python, SQL, Django', max_length=300),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('open', 'Published'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='open', max_length=12),
        ),
    ]
