# Generated by Django 6.1.1 on 2026-09-29 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_learningresource_studentlearningprogress'),
        ('roles', '0004_opportunity_details_and_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumereview',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='core.resume'),
        ),
        migrations.AddField(
            model_name='resumereview',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resumereview',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('changes_requested', 'Improvement Requested')], default='pending', max_length=20),
        ),
    ]
